import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        hello world {session?.user?.email}
        <section>
          <button onClick={() => signIn()}>Sign In</button>
          <br />
          <button onClick={() => signOut()}>Sign Out</button>
        </section>
      </main>
    </div>
  );
}
