import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  // Use session provides us with the current sesion (User logged in)
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* NOTE: We can't be certain that we will have the session  */}
        <h1>hello {session?.user?.name}</h1>

        <section>
          {session && (
            <div>You can only see this content when you're logged in</div>
          )}
        </section>

        <section>
          <button onClick={() => signIn()}>Sign In</button>
          <br />
          <button onClick={() => signOut()}>Sign Out</button>
        </section>
      </main>
    </div>
  );
}
